server:
  port: 8082
spring:
  datasource:
    url: jdbc:postgresql://localhost:5435/db_lumina_course
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    jdbc:
      lob:
        non_contextual_creation: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
